### ISSUE TITLE
Are node-fetch and chrome-launcher needed?

### ISSUE THREAD

**Issue by djpate** [VikashLoomba/AWS-Lambda-Docker#4]
Hello,

I'm trying to get my lambda to work but I'm still getting some pupeteer errors. I'm trying to mimick yours as much as possible so I was wondering if those two packages were actually needed? I don't see them used anywhere

**Comment by djpate** [comment]
got it working without it. Thanks

**Comment by TimotheeJeannin** [comment]
Hi @djpate.

Did you change anything in the `Dockerfile` or in the `app.js` file for this to work?

I tried to use the code as it is but I get this error: 

```
START RequestId: e4f651d0-911a-45a4-b891-95754481339f Version: $LATEST
2021-03-14T14:47:46.893Z	e4f651d0-911a-45a4-b891-95754481339f	INFO	{}
2021-03-14T14:48:17.371Z	e4f651d0-911a-45a4-b891-95754481339f	INFO	TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r818858 is guaranteed to work.
    at Timeout.onTimeout (/function/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:204:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
END RequestId: e4f651d0-911a-45a4-b891-95754481339f
REPORT RequestId: e4f651d0-911a-45a4-b891-95754481339f	Duration: 30480.97 ms	Billed Duration: 30481 ms	Memory Size: 1664 MB	Max Memory Used: 220 MB	
```

Tim

**Comment by djpate** [comment]
Hey @TimotheeJeannin ,

I only used this repo as a reference, mostly for the flags used in `app.js` for pupeteer.

I'm using my own docker image using alpine instead of debian. It's available on djpate/alpine-node-lambda:chromium if interested.
